# Generated by Django 5.2.11 on 2026-02-27 08:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceresponse',
            name='self_rating',
            field=models.IntegerField(blank=True, help_text='Self-rating 1–5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
