# Generated by Django 5.2.11 on 2026-02-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_add_self_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesession',
            name='ended_at',
            field=models.DateTimeField(blank=True, help_text='When the session ended (completed or time ran out).', null=True),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Optional time limit in minutes (e.g. 5, 10, 15). Null = no limit.', null=True),
        ),
    ]
