# Generated by Django 5.2.11 on 2026-02-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_add_timed_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesession',
            name='paused_at',
            field=models.DateTimeField(blank=True, help_text='When the timer was paused; None = running.', null=True),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='total_paused_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Total seconds the timer has been paused (extends effective end time).'),
        ),
    ]
