# Generated by Django 5.2.11 on 2026-02-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_add_timer_pause'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesession',
            name='timer_enabled',
            field=models.BooleanField(default=True, help_text='Whether to show the session timer (elapsed time, pause, end) on question pages.'),
        ),
    ]
